language: node_js
node_js:
    - "0.10.28"
before_script:
    - cp configs.js.EXAMPLE configs.js
notifications:
  email:
    recipients:
      - aidan.feldman@gsa.gov
      - alexander.magee@gsa.gov
      - raphael.villas@gsa.gov
