language: node_js
node_js:
    - "0.10.28"
before_script:
    - cp configs.js.EXAMPLE configs.js
notifications:
  email:
    recipients:
      - raphael.villas@gsa.gov
      - robert.read@gsa.gov
      - alexander.magee@gsa.gov
      - anna.flowerhorne@gsa.gov
